# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
      build_app(export_method: "development")
      pgyer(api_key: "f7116a8a272eaf69844e4ec0f4a823ce", user_key: "df5ae18e6c78b53d1838c595119a3487")

  end
end


